<a href="https://colab.research.google.com/github/Huzaifa-Alam/Python-Data_Analysis/blob/main/53_str.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
pokemon = pd.read_csv('/content/Pokemon.csv', index_col='#')
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
# USING STRING IN PANDASS
# pokemon['Name'].upper() # does not work
pokemon['Name'].str.upper()
pokemon['Name'].str.lower()
pokemon['Name'].str.swapcase()

# REVERSE STRING                            (*!*)
pokemon['Name'].str[::-1]
  # USING .str()  WE CAN USE ANY STRING METHOD ON THIS


# pokemon['Attack']
# pokemon['Attack'].str.upper() # it does not work with non values though

#
1                  ruasabluB
2                    ruasyvI
3                   ruasuneV
3      ruasuneV ageMruasuneV
4                 rednamrahC
               ...
719                  eicnaiD
719      eicnaiD ageMeicnaiD
720      denifnoC apooHapooH
720       dnuobnU apooHapooH
721                noinacloV
Name: Name, Length: 800, dtype: object

In [ ]:
filter = pokemon["Name"].str.contains('q', case = True) # csae sensitive only small q will appear
filter = pokemon["Name"].str.contains('q', case = False)
pokemon[filter]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False
155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False
156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
195,Quagsire,Water,Ground,430,95,85,85,65,65,35,2,False
211,Qwilfish,Water,Poison,430,65,95,75,55,55,85,2,False
284,Masquerain,Bug,Flying,414,70,60,62,80,82,60,3,False
384,Rayquaza,Dragon,Flying,680,105,150,90,150,90,95,3,True
384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
416,Vespiquen,Bug,Flying,474,70,80,102,80,102,40,4,False
520,Tranquill,Normal,Flying,358,62,77,62,50,42,65,5,False
651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False

In [ ]:
# STARTSWITH  AND ENDSWITH
name_filter = pokemon["Type 1"].str.startswith("W") # remeber that its case sensitive
name_filter = pokemon["Name"].str.startswith("Do") # remeber that its case sensitive
pokemon[name_filter]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
84,Doduo,Normal,Flying,310,35,85,45,35,35,75,1,False
85,Dodrio,Normal,Flying,460,60,110,70,60,60,100,1,False
232,Donphan,Ground,NaN,500,90,120,120,60,60,50,2,False
680,Doublade,Steel,Ghost,448,59,110,150,45,49,35,6,False

In [ ]:
end_filter = pokemon["Name"].str.endswith("er")
pokemon[end_filter]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
75,Graveler,Rock,Ground,390,55,95,115,45,45,35,1,False
88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
99,Kingler,Water,NaN,475,55,130,115,50,50,75,1,False
123,Scyther,Bug,Flying,500,70,110,80,55,80,105,1,False
194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
234,Stantler,Normal,NaN,465,73,95,62,85,65,85,2,False
279,Pelipper,Water,Flying,430,60,50,100,85,70,65,3,False
320,Wailmer,Water,NaN,400,130,70,35,70,35,60,3,False
336,Seviper,Poison,NaN,458,73,100,60,100,60,65,3,False
459,Snover,Grass,Ice,334,60,62,50,62,60,40,4,False
507,Herdier,Normal,NaN,370,65,80,65,35,65,60,5,False
589,Escavalier,Bug,Steel,495,70,135,105,60,105,20,5,False
657,Frogadier,Water,NaN,405,54,63,52,83,56,97,6,False
662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
692,Clauncher,Water,NaN,330,50,53,62,58,63,44,6,False
693,Clawitzer,Water,NaN,500,71,73,88,120,89,59,6,False

In [ ]:
pokemon['Type 1'].str.replace('Grass' , 'HUZAIFA ' , regex = False)

#
1                  Bulbasaur
2                    Ivysaur
3                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
719                  Diancie
719      DiancieMega Diancie
720      HoopaHoopa Confined
720       HoopaHoopa Unbound
721                Volcanion
Name: Type 1, Length: 800, dtype: object

In [ ]:
# REPLACE ()
# pokemon['Type 1'] =  pokemon['Type 1'].str.replace('Grass' , 'HUZAIFA ' , regex = False) # by default regex = False (REGEX MEANS + * /  -)

# pokemon[pokemon['Type 1']=='HUZAIFA']   # DISPLAY ALL THE UHZAIFA
pokemon['Type 1'] = pokemon['Type 1'].str.replace('Grass', 'HUZAIFA', regex=False)

# Displaying all rows where 'Type 1' is 'HUZAIFA'
pokemon[pokemon['Type 1'] == 'HUZAIFA']

Empty DataFrame
Columns: [Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [ ]:
# index and column
col = pd.read_csv('/content/Pokemon.csv' , index_col="Name")
col

,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,680,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
col.columns.str.upper()

Index(['#', 'TYPE 1', 'TYPE 2', 'TOTAL', 'HP', 'ATTACK', 'DEFENSE', 'SP. ATK',
       'SP. DEF', 'SPEED', 'GENERATION', 'LEGENDARY'],
      dtype='object')

In [ ]:
col.columns = col.columns.str.upper()
col

,#,TYPE 1,TYPE 2,TOTAL,HP,ATTACK,DEFENSE,SP. ATK,SP. DEF,SPEED,GENERATION,LEGENDARY
Name,,,,,,,,,,,,
Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,719,Rock,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,719,Rock,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,720,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,720,Psychic,Dark,680,80,160,60,170,130,80,6,True
Volcanion,721,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
col.index = col.index.str[:5] # our index name is Name
col.index = col.index.str.upper()
col

,#,TYPE 1,TYPE 2,TOTAL,HP,ATTACK,DEFENSE,SP. ATK,SP. DEF,SPEED,GENERATION,LEGENDARY
Name,,,,,,,,,,,,
BULBA,1,Grass,Poison,318,45,49,49,65,65,45,1,False
IVYSA,2,Grass,Poison,405,60,62,63,80,80,60,1,False
VENUS,3,Grass,Poison,525,80,82,83,100,100,80,1,False
VENUS,3,Grass,Poison,625,80,100,123,122,120,80,1,False
CHARM,4,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
DIANC,719,Rock,Fairy,600,50,100,150,100,150,50,6,True
DIANC,719,Rock,Fairy,700,50,160,110,160,110,110,6,True
HOOPA,720,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HOOPA,720,Psychic,Dark,680,80,160,60,170,130,80,6,True
VOLCA,721,Fire,Water,600,80,110,120,130,90,70,6,True