<a href="https://colab.research.google.com/github/Huzaifa-Alam/Python-Data_Analysis/blob/main/SEC_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
pokemon  = pd.read_csv("/content/Pokemon.csv" , index_col = "#")
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
pokemon.info()# only missing values in (type 2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 800 entries, 1 to 721
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   Type 2      414 non-null    object
 3   Total       800 non-null    int64
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 75.8+ KB

In [ ]:
pokemon.describe().round() # get each numeric value

       Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
count  800.0  800.0   800.0    800.0    800.0    800.0  800.0       800.0
mean   435.0   69.0    79.0     74.0     73.0     72.0   68.0         3.0
std    120.0   26.0    32.0     31.0     33.0     28.0   29.0         2.0
min    180.0    1.0     5.0      5.0     10.0     20.0    5.0         1.0
25%    330.0   50.0    55.0     50.0     50.0     50.0   45.0         2.0
50%    450.0   65.0    75.0     70.0     65.0     70.0   65.0         3.0
75%    515.0   80.0   100.0     90.0     95.0     90.0   90.0         5.0
max    780.0  255.0   190.0    230.0    194.0    230.0  180.0         6.0

In [ ]:
pokemon.describe(exclude=['int','float']) # get info which is not numeric

 # false has 735 frequency which are not legendary

             Name Type 1  Type 2 Legendary
count         800    800     414       800
unique        800     18      18         2
top     Bulbasaur  Water  Flying     False
freq            1    112      97       735

A P P L Y ()

>applies to a function to a series

In [ ]:
# crete new column
pokemon["name_length"] = pokemon["Name"].apply(len) # apply length function to each element # determine the length of every name
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,name_length
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,9
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,7
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,8
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,21
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,7
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,19
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,19
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,18
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,9

In [ ]:
del pokemon["name_length"] # delete the name_length column
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
          # attack type of int
def strength(attack):
  if attack > 150:
    return 'strong'
  elif attack>100:
    return 'average'
  else:
    return 'weak'

In [ ]:
pokemon["strength"]  =  pokemon["Attack"].apply(strength)
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,strength
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,weak
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,weak
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,weak
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,weak
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,weak
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,weak
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,strong
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,average
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,strong
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,average

In [ ]:
#value_counts()  returns object(STRING) containing counts of unique values.   counts the valus of the given column
pokemon.value_counts(["strength"])

# HANDLE ALL THE CASES OTHERWISE IT WILL RETURN NaN

strength
weak        630
average     152
strong       18
dtype: int64

In [ ]:
del pokemon['strength']

In [ ]:
#  APPLY ALSO USE WITH MULTIPPLE COLUMNS
def score(row):
  attack= row['Attack']  # we can also use the index as a column
  defense= row["Defense"]
  speed= row["Speed"]
  return sum([attack,defense,speed])

In [ ]:
# pokemon['sum'] = pokemon["Attack"].apply(sum)
# pokemon
pokemon['TOTAL SCORE OF ATTACK,DEFENSE & SPEED'] = pokemon.apply(score ,axis = 1)
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,SCORE,"TOTAL SCORE OF ATTACK,DEFENSE & SPEED"
#,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,143,143
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,185,185
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,245,245
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,303,303
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,160,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,300,300
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,380,380
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,240,240
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,300,300
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,300,300

In [ ]:

# we can use lamda
short_name = pokemon["Name"].apply (lambda x: x[0:5])
pokemon.insert(1 , 'shortnamess',short_name) # insert new column , name of column will be shortname, varible
pokemon

,Name,shortnamess,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,,
1,Bulbasaur,Bulba,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Ivysa,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Venus,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Venus,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Charm,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Dianc,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Dianc,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Hoopa,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Hoopa,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Volca,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
del pokemon['shortnamess']

In [ ]:
import pandas as pd
pokemon  = pd.read_csv("/content/Pokemon.csv" , index_col = "#")
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True



*  map () MAPS A SERIES

*  applymap()apply a function throught out the dataframe

In [ ]:
pokemon["Legendary"] =  pokemon["Legendary"].map({False: "No" , True: 'Yes'}) # changng values  igues like this
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,No
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,No
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,No
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,No
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,No
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,Yes
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,Yes
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,Yes
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,Yes
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,Yes

In [ ]:
pokemon['Generation'] = pokemon['Generation'].map({1: "ONE",2: "TWO",3: "THREE",4: "FOUR",5: "FIVE",6: "SIX"})
# value that are not specified will be convert into NaN
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,ONE,No
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,ONE,No
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,ONE,No
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,ONE,No
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,ONE,No
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,SIX,Yes
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,SIX,Yes
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,SIX,Yes
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,SIX,Yes
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,SIX,Yes

In [ ]:
# applymap()   apply a function throught out the dataframe
pokemon.applymap(type)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
2,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
4,<class 'str'>,<class 'str'>,<class 'float'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
...,...,...,...,...,...,...,...,...,...,...,...,...
719,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
719,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
720,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
720,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>
721,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>

In [ ]:
def uppercase(var: str)-> str:
  return var.upper

In [ ]:
# pokemon['capital'] = pokemon['Total'].apply(uppercase)
# pokemon
pokemon = pokemon.applymap(str)
pokemon.applymap(uppercase)
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,ONE,No
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,ONE,No
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,ONE,No
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,ONE,No
4,Charmander,Fire,nan,309,39,52,43,60,50,65,ONE,No
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,SIX,Yes
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,SIX,Yes
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,SIX,Yes
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,SIX,Yes
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,SIX,Yes

In [ ]:
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,one & zero
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,0.0
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.0
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.0
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1.0
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.0
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.0
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1.0
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1.0

In [ ]:

pokemon['one & zero'] = pokemon['Legendary'].astype('float')
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,one & zero
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,0.0
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.0
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.0
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,1.0
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.0
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.0
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,1.0
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,1.0

In [ ]:

sec_gen = pokemon['Generation'] == 2
pokemon[sec_gen]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,one & zero
#,,,,,,,,,,,,,
152,Chikorita,Grass,NaN,318,45,49,65,49,65,45,2,False,0.0
153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False,0.0
154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False,0.0
155,Cyndaquil,Fire,NaN,309,39,52,43,60,50,65,2,False,0.0
156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False,0.0
248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False,0.0
249,Lugia,Psychic,Flying,680,106,90,130,90,154,110,2,True,1.0
250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True,1.0
251,Celebi,Psychic,Grass,600,100,100,100,100,100,100,2,False,0.0

In [ ]:
# # we can also use  where() which return NaN if value is not found
pokemon.where(pokemon['Generation'] == 2) # we wuse dropna() to see what is filtered
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,one & zero
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,0.0
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.0
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.0
4,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
719,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
720,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
720,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
721,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====

In [ ]:
pokemon.where(pokemon['Generation'] == 2).dropna() # we wuse dropna() to see what is filtered
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,one & zero
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,0.0
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.0
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.0
4,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
719,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
720,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
720,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
721,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====

In [ ]:
pokemon = pokemon.where(pokemon['Type 1'] == 'Grass' , other = '=====').dropna()
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,one & zero
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,0.0
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.0
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.0
4,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
719,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
720,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
720,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====
721,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====,=====

In [ ]:
pokemon["Type 1"]

#
1      Grass
2      Grass
3      Grass
3      Grass
4      =====
       ...
719    =====
719    =====
720    =====
720    =====
721    =====
Name: Type 1, Length: 800, dtype: object

agg()**bold text**

1.  is used to aggregate one or more operatoins over the specified axis
2.

In [ ]:
pokemon  = pd.read_csv("/content/Pokemon.csv" )
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
 pokemon.agg({'Attack': 'mean' ,'Defense': 'max'})

Attack      79.00125
Defense    230.00000
dtype: float64

In [ ]:
# you can use multiple to specify
pokemon.agg({'Attack': ['mean','max','std'] ,'Defense': ['mean','max','std']})

          Attack     Defense
mean   79.001250   73.842500
max   190.000000  230.000000
std    32.457366   31.183501

In [ ]:
# YOU CAN SEE THE ALOTS OF MTHODS HERE
pokemon.describe()

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [ ]:
# can also be used without dictionary
# pokemon.agg('max', numeric_only=True )
# pokemon.agg('min', numeric_only=True )
pokemon.agg('mean', numeric_only=True ).round(3)

Total         435.102
HP             69.259
Attack         79.001
Defense        73.842
Sp. Atk        72.820
Sp. Def        71.902
Speed          68.278
Generation      3.324
Legendary       0.081
dtype: float64

In [ ]:
pokemon.set_index(['Name','Type 1','Attack'] , inplace = True) # now name and Type set as index
pokemon

,,,#,Type 2,Total,HP,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 1,Attack,,,,,,,,,,
Bulbasaur,Grass,49,1,Poison,318,45,49,65,65,45,1,False
Ivysaur,Grass,62,2,Poison,405,60,63,80,80,60,1,False
Venusaur,Grass,82,3,Poison,525,80,83,100,100,80,1,False
VenusaurMega Venusaur,Grass,100,3,Poison,625,80,123,122,120,80,1,False
Charmander,Fire,52,4,NaN,309,39,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Rock,100,719,Fairy,600,50,150,100,150,50,6,True
DiancieMega Diancie,Rock,160,719,Fairy,700,50,110,160,110,110,6,True
HoopaHoopa Confined,Psychic,110,720,Ghost,600,80,60,150,130,70,6,True
HoopaHoopa Unbound,Psychic,160,720,Dark,680,80,60,170,130,80,6,True
Volcanion,Fire,110,721,Water,600,80,120,130,90,70,6,True

In [ ]:
pokemon.index # return each index as  a tuple

MultiIndex([(                'Bulbasaur',   'Grass',  49),
            (                  'Ivysaur',   'Grass',  62),
            (                 'Venusaur',   'Grass',  82),
            (    'VenusaurMega Venusaur',   'Grass', 100),
            (               'Charmander',    'Fire',  52),
            (               'Charmeleon',    'Fire',  64),
            (                'Charizard',    'Fire',  84),
            ('CharizardMega Charizard X',    'Fire', 130),
            ('CharizardMega Charizard Y',    'Fire', 104),
            (                 'Squirtle',   'Water',  48),
            ...
            (                   'Noibat',  'Flying',  30),
            (                  'Noivern',  'Flying',  70),
            (                  'Xerneas',   'Fairy', 131),
            (                  'Yveltal',    'Dark', 131),
            (         'Zygarde50% Forme',  'Dragon', 100),
            (                  'Diancie',    'Rock', 100),
            (      'DiancieMega Diancie',    'Rock', 160),
            (      'HoopaHoopa Confined', 'Psychic', 110),
            (       'HoopaHoopa Unbound', 'Psychic', 160),
            (                'Volcanion',    'Fire', 110)],
           names=['Name', 'Type 1', 'Attack'], length=800)

In [ ]:
# USE get_level_values() TO SPECIFY WHICH INDEX YOU WANT TO GET BACK
# pokemon.index.get_level_values(1)
pokemon.index.get_level_values(0) # that means whether we want the name index back or Type 1 index back
pokemon.index.get_level_values('Name') # that means whether we want the name index back or Type 1 index back

Index(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard', 'CharizardMega Charizard X',
       'CharizardMega Charizard Y', 'Squirtle',
       ...
       'Noibat', 'Noivern', 'Xerneas', 'Yveltal', 'Zygarde50% Forme',
       'Diancie', 'DiancieMega Diancie', 'HoopaHoopa Confined',
       'HoopaHoopa Unbound', 'Volcanion'],
      dtype='object', name='Name', length=800)

In [ ]:
# YOU CAN ALSO SWAP THE LEVELS USING swap.level()
pokemon = pokemon.swaplevel()  # rpeating values outer (outside)
pokemon

,,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 1,,,,,,,,,,
Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
pokemon.sort_values('Type 1')

,,,#,Type 2,Total,HP,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 1,Attack,,,,,,,,,,
Sewaddle,Bug,53,540,Grass,310,45,70,40,60,42,5,False
Pinsir,Bug,125,127,NaN,500,65,100,55,70,85,1,False
Burmy,Bug,29,412,NaN,224,40,45,29,45,36,4,False
Scyther,Bug,110,123,Flying,500,70,80,55,80,105,1,False
Joltik,Bug,47,595,Electric,319,50,50,57,50,65,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Totodile,Water,65,158,NaN,314,50,64,44,48,43,2,False
Basculin,Water,92,550,NaN,460,70,65,80,55,98,5,False
Vaporeon,Water,65,134,NaN,525,130,60,110,95,65,1,False
Panpour,Water,53,515,NaN,316,50,48,53,48,64,5,False
Chinchou,Water,38,170,Electric,330,75,38,56,56,67,2,False

In [ ]:
pokemon = pd.read_csv("/content/Pokemon.csv" , index_col=['Type 1','Name'] )
pokemon

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

In [ ]:
# pokemon.loc['Totodile']
pokemon.loc['Grass'] # select alll the grass pokemon

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Bulbasaur,1,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,2,Poison,405,60,62,63,80,80,60,1,False
Venusaur,3,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,3,Poison,625,80,100,123,122,120,80,1,False
Oddish,43,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...
Chespin,650,NaN,313,56,61,65,48,45,38,6,False
Quilladin,651,NaN,405,61,78,95,56,58,57,6,False
Chesnaught,652,Fighting,530,88,107,122,74,75,64,6,False
Skiddo,672,NaN,350,66,65,48,62,57,52,6,False
Gogoat,673,NaN,531,123,100,62,97,81,68,6,False

In [ ]:
pokemon.loc['Grass','Attack'] # select a specific column (Attack)

Name
Bulbasaur                 49
Ivysaur                   62
Venusaur                  82
VenusaurMega Venusaur    100
Oddish                    50
                        ...
Chespin                   61
Quilladin                 78
Chesnaught               107
Skiddo                    65
Gogoat                   100
Name: Attack, Length: 70, dtype: int64

In [ ]:
# use braces for multiple indices (indexs)
# WE HV TO SELECT THE TYPE FIRST THEN NAME
pokemon.loc[('Grass','Bulbasaur') ]
pokemon.loc[('Grass','Bulbasaur') , 'Attack']
pokemon.loc[('Grass','Bulbasaur') , ['Attack','Defense']]

Attack     49
Defense    49
Name: (Grass, Bulbasaur), dtype: int64

In [ ]:
# HOME WORK ( hw ) ASSIGNMENT
hw = pd.read_csv("/content/Pokemon.csv" , index_col=['Type 1','Name'] )
hw

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

In [ ]:
hw.sort_values('Type 1', inplace = True)
hw

                    #    Type 2  Total   HP  Attack  Defense  Sp. Atk  \
Type 1 Name
Bug    Sewaddle   540     Grass    310   45      53       70       40
       Spinarak   167    Poison    250   40      60       40       40
       Ledian     166    Flying    390   55      35       50       55
       Nincada    290    Ground    266   31      45       90       30
       Ledyba     165    Flying    265   40      20       30       40
...               ...       ...    ...  ...     ...      ...      ...
Water  Gastrodon  423    Ground    475  111      83       68       92
       Shellos    422       NaN    325   76      48       48       57
       Floatzel   419       NaN    495   85     105       55       85
       Clamperl   366       NaN    345   35      64       85       74
       Chinchou   170  Electric    330   75      38       38       56

                  Sp. Def  Speed  Generation  Legendary
Type 1 Name
Bug    Sewaddle        60     42           5      False
       Spinarak        40     30           2      False
       Ledian         110     85           2      False
       Nincada         30     40           3      False
       Ledyba          80     55           2      False
...                   ...    ...         ...        ...
Water  Gastrodon       82     39           4      False
       Shellos         62     34           4      False
       Floatzel        50    115           4      False
       Clamperl        55     32           3      False
       Chinchou        56     67           2      False

[800 rows x 11 columns]

In [ ]:
# select all the star pokemon that start with C
firehw = hw.loc[('Fire')]
start_with_C = firehw.index.str.startswith('C')
firehw[start_with_C] # i guess here only varible

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Charizard,6,Flying,534,78,84,78,109,85,100,1,False
CharizardMega Charizard X,6,Dragon,634,78,130,111,130,85,100,1,False
CharizardMega Charizard Y,6,Flying,634,78,104,78,159,115,100,1,False
Charmeleon,5,NaN,405,58,64,58,80,65,80,1,False
Charmander,4,NaN,309,39,52,43,60,50,65,1,False
Cyndaquil,155,NaN,309,39,52,43,60,50,65,2,False
Camerupt,323,Ground,460,70,100,70,105,75,40,3,False
Chimchar,390,NaN,309,44,58,44,58,44,61,4,False
Combusken,256,Fighting,405,60,85,60,85,60,55,3,False
CameruptMega Camerupt,323,Ground,560,70,120,100,145,105,20,3,False

In [ ]:
hw.agg({'Attack': ['max','min','mean'], 'Defense': ['max','min','mean']}).round()

      Attack  Defense
max    190.0    230.0
min      5.0      5.0
mean    79.0     74.0